### ISSUE TITLE
Theme partially broken as of last few days

### ISSUE THREAD

**Issue by Skyyblaze** [DamianSowinski/whatsapp#2]
I've been using the Transparent WhatsApp theme since a long time now but sadly as of a few days it's been partially broken. The contact/chat-list is covered by a translucent white layer and the Media-Upload dialog appears very squished.

**Comment by DamianSowinski** [comment]
Hi,
Thanks for information. I will fixed it this weekend.

Regards
Damian

From: ***@***.***>
Sent: poniedziałek, 27 marca 2023 15:49
To: ***@***.***>
Cc: ***@***.***>
Subject: [DamianSowinski/whatsapp] Theme partially broken as of last few days (Issue #2)


I've been using the Transparent WhatsApp theme since a long time now but sadly as of a few days it's been partially broken. The contact/chat-list is covered by a translucent white layer and the Media-Upload dialog appears very squished.

**Comment by DamianSowinski** [comment]
Style updated

**Comment by Skyyblaze** [comment]
Sadly the style got broken again, everything is extremely squished

**Comment by DamianSowinski** [comment]
Hi,
fixed, new version is here: v1.0.3<https://github.com/DamianSowinski/whatsapp/blob/v1.0.3/whatsapp-blur.user.styl>

Regards
Damian Sowiński

________________________________
Od: Skyyblaze ***@***.***>
Wysłane: wtorek, 12 grudnia 2023 20:45
Do: DamianSowinski/whatsapp ***@***.***>
DW: Damian Sowiński ***@***.***>; Assign ***@***.***>
Temat: Re: [DamianSowinski/whatsapp] Theme partially broken as of last few days (Issue #2)


Sadly the style got broken again, everything is extremely squished
